name: Create Submodule

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write  # Grant write permissions to allow creating and pushing tags

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      folder_changed: ${{ steps.check_changes.outputs.SUBMODULE_CHANGED }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Get the previous tag
        id: get_prev_tag
        run: |
          git tag --list 'v*' --sort=-creatordate
          # Get the previous tag before the current one
          PREV_TAG=$(git tag --list 'v*' --sort=-creatordate | tail -n +2 | head -n 1)
          echo "Current tag is ${{ github.ref_name }}"
          echo "Previous tag is $PREV_TAG"
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Check for changes in the folder
        id: check_changes
        run: |
          # Compare changes between the previous tag and the current tag in the target folder
          if git diff --name-only ${{ env.PREV_TAG }} HEAD -- pkg/math | grep -q .; then
            echo "Changes detected in the submodule"
            echo "SUBMODULE_CHANGED=true" >> $GITHUB_OUTPUT"
          else
            echo "No changes in the submodule"
            echo "SUBMODULE_CHANGED=false" >> $GITHUB_OUTPUT"
          fi  

  create-tag:
    name: Create submodule package tag
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.folder_changed == 'true'

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract Tag from Release
        id: extract_tag
        run: |
          tag_name="${{ github.ref_name }}"
          echo "tag_name=$tag_name" >> $GITHUB_ENV

      - name: Create and Push New Tag
        run: |
          new_tag="pkg/math/${{ env.tag_name }}"
          git tag "$new_tag"
          git push origin "$new_tag"
